<#
.SYNOPSIS
    Sorts instrumentals from "Music Albums\Not Sorted" into their album folders.

.DESCRIPTION
    Each file is matched to an artist/album/track in this order:
      1. a YouTube video ID in the file name (yt-dlp adds "[xxxxxxxxxxx]" by default)
         that is one of the links in instrumental_links.txt or
         missing_instrumental_links.txt
      2. the file name containing a video title from the list
      3. the artist name plus a track name from the album tracklists

    It then finds the album's folder under "Music Albums" (e.g. "Yeat - 2093",
    "Yeat\2093" or "2093 (2024)"). If no folder exists yet it creates
    "<Artist> - <Album>", or "<Album>" inside an existing artist folder.

    By default nothing is moved: it prints the plan and saves it to
    sort_plan.csv in "Music Albums". Run again with -Apply to move the files.
    Files it can't place stay in "Not Sorted", and so does a song the album
    folder already has (listed as "duplicate"). Every move is logged to
    sort_log.csv so it can be undone.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\sort_not_sorted.ps1
    powershell -ExecutionPolicy Bypass -File .\sort_not_sorted.ps1 -Apply

.NOTES
    Generated by scripts/make_sorter.py. Edit the template, not this file.
#>
[CmdletBinding()]
param(
    [string]$Root = (Join-Path ([Environment]::GetFolderPath('Desktop')) 'Music Albums'),
    [string]$Unsorted,
    [switch]$Apply
)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'
if (-not $Unsorted) { $Unsorted = Join-Path $Root 'Not Sorted' }
if (-not (Test-Path -LiteralPath $Unsorted -PathType Container)) {
    throw "Folder not found: $Unsorted"
}
$Root = (Resolve-Path -LiteralPath $Root).Path
$Unsorted = (Resolve-Path -LiteralPath $Unsorted).Path
$Sep = [IO.Path]::DirectorySeparatorChar

$AudioExtensions = @('.mp3', '.m4a', '.wav', '.flac', '.aac', '.ogg', '.opus', '.webm',
                     '.mp4', '.mkv', '.wma', '.aif', '.aiff', '.alac')
$FolderNoise = @('album', 'deluxe', 'instrumentals', 'instrumental', 'mixtape', 'ep')

function Get-Norm([string]$s) {
    # Lowercase, strip accents (ë -> e, ³ -> 3, fullwidth -> ascii), punctuation -> spaces.
    if (-not $s) { return '' }
    $d = $s.Normalize([Text.NormalizationForm]::FormKD)
    $sb = New-Object Text.StringBuilder
    foreach ($c in $d.ToCharArray()) {
        if ([Globalization.CharUnicodeInfo]::GetUnicodeCategory($c) -eq
            [Globalization.UnicodeCategory]::NonSpacingMark) { continue }
        if ([char]::IsLetterOrDigit($c)) { [void]$sb.Append([char]::ToLowerInvariant($c)) }
        else { [void]$sb.Append(' ') }
    }
    return (($sb.ToString() -replace '\s+', ' ').Trim())
}

function Get-NormAccent([string]$s) {
    # Like Get-Norm but keeps accents, so "Back homë" and "Back Home" differ.
    if (-not $s) { return '' }
    $s = $s.Normalize([Text.NormalizationForm]::FormC).ToLowerInvariant()
    return (($s -replace '[^\p{L}\p{N}]+', ' ').Trim())
}

function Test-Words([string]$hay, [string]$needle) {
    # True when $needle appears in $hay as whole words.
    if (-not $needle) { return $false }
    return (" $hay ").Contains(" $needle ")
}

function Remove-WordsOnce([string]$hay, [string]$needle) {
    if (-not $needle) { return $hay }
    $padded = " $hay "
    $i = $padded.IndexOf(" $needle ")
    if ($i -lt 0) { return $hay }
    return (($padded.Remove($i, $needle.Length + 1)) -replace '\s+', ' ').Trim()
}

# ---------------------------------------------------------------------------
# Album data (from data/tracklists.md, data/results.tsv and data/extra_links.tsv)
# ---------------------------------------------------------------------------
$json = @'
__ALBUM_DATA__
'@
$Albums = ConvertFrom-Json $json

$Entries = New-Object System.Collections.ArrayList
$ById = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
$ByTitle = @{}
$TrackNameCount = @{}

foreach ($a in $Albums) {
    $a | Add-Member NoteProperty ArtistNorms @(@(Get-Norm $a.artist) + @($a.artistAliases | ForEach-Object { Get-Norm $_ }) | Where-Object { $_ })
    $a | Add-Member NoteProperty AlbumNorms @(@(Get-Norm $a.album) + @($a.albumAliases | ForEach-Object { Get-Norm $_ }) | Where-Object { $_ })
    $a | Add-Member NoteProperty Key "$($a.artist)|$($a.album)"
    foreach ($t in $a.tracks) {
        # Other spellings a file name may use ("Mornin Mudd" for "Morning mudd").
        $norms = @(@(Get-Norm $t.name) + @($t.aliases | ForEach-Object { Get-Norm $_ }) | Where-Object { $_ } | Select-Object -Unique)
        $e = [pscustomobject]@{ Album = $a; Track = $t.name; TrackNorms = $norms }
        [void]$Entries.Add($e)
        foreach ($id in $t.ids) { $ById[$id] = $e }
        foreach ($title in $t.titles) {
            $n = Get-Norm $title
            if ($n.Length -lt 12) { continue }
            # Different songs can share a title once accents are stripped
            # ("Back homë" / "BACK HOME"), so keep every entry per title.
            if (-not $ByTitle.ContainsKey($n)) { $ByTitle[$n] = New-Object System.Collections.ArrayList }
            [void]$ByTitle[$n].Add([pscustomobject]@{ Entry = $e; Accent = (Get-NormAccent $title) })
        }
        foreach ($tn in $norms) { $TrackNameCount[$tn] = 1 + [int]$TrackNameCount[$tn] }
    }
}

function Find-Track([string]$baseName) {
    # Returns @(entry, how) or @($null, reason).
    for ($i = 0; $i -le $baseName.Length - 11; $i++) {
        $id = $baseName.Substring($i, 11)
        if ($ById.ContainsKey($id)) { return @($ById[$id], 'video id') }
    }

    $n = Get-Norm $baseName
    $best = $null
    if ($ByTitle.ContainsKey($n)) { $best = $n }
    else {
        foreach ($k in $ByTitle.Keys) {
            if ((Test-Words $n $k) -and (-not $best -or $k.Length -gt $best.Length)) { $best = $k }
        }
    }
    if ($best) {
        $hits = @($ByTitle[$best])
        if (@($hits | ForEach-Object { "$($_.Entry.Album.Key)|$($_.Entry.Track)" } | Select-Object -Unique).Count -gt 1) {
            $na = Get-NormAccent $baseName
            $hits = @($hits | Where-Object { Test-Words $na $_.Accent })
        }
        $keys = @($hits | ForEach-Object { "$($_.Entry.Album.Key)|$($_.Entry.Track)" } | Select-Object -Unique)
        if ($keys.Count -eq 1) { return @($hits[0].Entry, 'video title') }
        $why = 'ambiguous: ' + ((@($ByTitle[$best]) | ForEach-Object { "$($_.Entry.Album.album) / $($_.Entry.Track)" }) -join ' or ')
        return @($null, $why)
    }

    $cands = @()
    foreach ($e in $Entries) {
        $hit = @($e.TrackNorms | Where-Object { Test-Words $n $_ } | Sort-Object Length -Descending) | Select-Object -First 1
        if (-not $hit) { continue }
        $artistHit = @($e.Album.ArtistNorms | Where-Object { Test-Words $n $_ }).Count -gt 0
        # Look for the album name outside the track name, so a title track
        # ("LYFESTYLE" on LYFESTYLE) doesn't count as naming the album.
        $rest = Remove-WordsOnce $n $hit
        $albumHit = @($e.Album.AlbumNorms | Where-Object { Test-Words $rest $_ }).Count -gt 0
        $cands += [pscustomobject]@{ Entry = $e; ArtistHit = $artistHit; Norm = $hit
            Score = $hit.Length + $(if ($albumHit) { 500 } else { 0 }) }
    }
    if (-not $cands) { return @($null, 'no track name matched') }

    $withArtist = @($cands | Where-Object { $_.ArtistHit })
    if ($withArtist) { $cands = $withArtist }
    else {
        $c = $cands | Sort-Object Score -Descending | Select-Object -First 1
        if ($TrackNameCount[$c.Norm] -eq 1 -and $c.Norm.Length -ge 6) {
            return @($c.Entry, 'track name only')
        }
        return @($null, 'track name found but no artist in file name')
    }

    $top = ($cands | Measure-Object Score -Maximum).Maximum
    $winners = @($cands | Where-Object { $_.Score -eq $top })
    $keys = @($winners | ForEach-Object { $_.Entry.Album.Key } | Select-Object -Unique)
    if ($keys.Count -gt 1) {
        $why = 'ambiguous: ' + (($winners | ForEach-Object { "$($_.Entry.Album.album) / $($_.Entry.Track)" }) -join ' or ')
        return @($null, $why)
    }
    return @($winners[0].Entry, 'artist + track name')
}

# ---------------------------------------------------------------------------
# Album folders
# ---------------------------------------------------------------------------
$Folders = @(Get-ChildItem -LiteralPath $Root -Directory -Recurse -Depth 2 -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -ne $Unsorted -and -not $_.FullName.StartsWith($Unsorted + $Sep) })
$FolderInfo = foreach ($f in $Folders) {
    $leaf = Get-Norm $f.Name
    foreach ($w in $FolderNoise) { $leaf = Remove-WordsOnce $leaf $w }
    # Keep both: "2093 (2024)" must still match the album called 2093.
    $noYear = ($leaf -replace '\b(19|20)\d\d\b', '' -replace '\s+', ' ').Trim()
    [pscustomobject]@{ Dir = $f; Leafs = @(@($leaf, $noYear) | Select-Object -Unique); Path = (Get-Norm $f.FullName.Substring($Root.Length))
        HasSubdirs = [bool](Get-ChildItem -LiteralPath $f.FullName -Directory -ErrorAction SilentlyContinue | Select-Object -First 1) }
}

$FolderCache = @{}
function Get-AlbumFolder($a) {
    if ($FolderCache.ContainsKey($a.Key)) { return $FolderCache[$a.Key] }
    $found = @()
    foreach ($fi in $FolderInfo) {
        $strong = $false; $weak = $false
        foreach ($leaf in $fi.Leafs) {
            $stripped = $leaf
            foreach ($an in $a.ArtistNorms) { $stripped = Remove-WordsOnce $stripped $an }
            if ($a.AlbumNorms -contains $stripped) { $strong = $true }
            if ((-not $fi.HasSubdirs) -and ($a.AlbumNorms -contains $leaf)) { $weak = $true }
        }
        if (-not ($strong -or $weak)) { continue }
        $artistInPath = @($a.ArtistNorms | Where-Object { Test-Words $fi.Path $_ }).Count -gt 0
        $found += [pscustomobject]@{ Info = $fi
            Rank = $(if ($strong) { 2 } else { 0 }) + $(if ($artistInPath) { 1 } else { 0 }) }
    }
    if ($found) {
        $pick = $found | Sort-Object @{ e = 'Rank'; Descending = $true }, @{ e = { $_.Info.Dir.FullName.Length } } |
            Select-Object -First 1
        $res = [pscustomobject]@{ Path = $pick.Info.Dir.FullName; New = $false }
    } else {
        $name = $a.album
        if ($name -match '[<>:"/\\|?*]') { $name = $a.albumAliases[0] }
        # Only a folder that already holds album folders counts as an artist folder;
        # a bare "Playboi Carti (2017)" is the self-titled album, not the artist.
        $artistDir = $FolderInfo | Where-Object {
            $fi = $_; $fi.HasSubdirs -and @($fi.Leafs | Where-Object { $a.ArtistNorms -contains $_ }).Count -gt 0
        } | Select-Object -First 1
        if ($artistDir) { $path = Join-Path $artistDir.Dir.FullName $name }
        else { $path = Join-Path $Root "$($a.artist) - $name" }
        $res = [pscustomobject]@{ Path = $path; New = $true }
    }
    $FolderCache[$a.Key] = $res
    return $res
}

$HaveCache = @{}
function Get-HaveTracks($dest) {
    # Tracks already in an album folder, as "artist|album|track" -> file name,
    # so a second copy of a song isn't moved in next to the first.
    if ($HaveCache.ContainsKey($dest.Path)) { return $HaveCache[$dest.Path] }
    $have = @{}
    if (-not $dest.New -and (Test-Path -LiteralPath $dest.Path)) {
        foreach ($g in Get-ChildItem -LiteralPath $dest.Path -File) {
            if ($AudioExtensions -notcontains $g.Extension.ToLowerInvariant()) { continue }
            $m = Find-Track $g.BaseName
            if ($m[0]) { $have["$($m[0].Album.Key)|$($m[0].Track)"] = $g.Name }
        }
    }
    $HaveCache[$dest.Path] = $have
    return $have
}

# ---------------------------------------------------------------------------
# Plan
# ---------------------------------------------------------------------------
$files = @(Get-ChildItem -LiteralPath $Unsorted -File -Recurse)
Write-Host "Found $($files.Count) files in $Unsorted"
$plan = foreach ($f in $files) {
    if ($AudioExtensions -notcontains $f.Extension.ToLowerInvariant()) {
        [pscustomobject]@{ File = $f.FullName; Artist = ''; Album = ''; Track = ''; MatchedBy = ''
            Destination = ''; NewFolder = ''; Status = 'skipped: not an audio file' }
        continue
    }
    $r = Find-Track $f.BaseName
    if (-not $r[0]) {
        [pscustomobject]@{ File = $f.FullName; Artist = ''; Album = ''; Track = ''; MatchedBy = ''
            Destination = ''; NewFolder = ''; Status = "unmatched: $($r[1])" }
        continue
    }
    $e = $r[0]; $dest = Get-AlbumFolder $e.Album
    $status = 'move'
    $have = Get-HaveTracks $dest
    $key = "$($e.Album.Key)|$($e.Track)"
    if ($have.ContainsKey($key)) { $status = "duplicate: album already has $($have[$key])" }
    else { $have[$key] = $f.Name }
    [pscustomobject]@{ File = $f.FullName; Artist = $e.Album.artist; Album = $e.Album.album; Track = $e.Track
        MatchedBy = $r[1]; Destination = $dest.Path; NewFolder = $(if ($dest.New) { 'yes' } else { '' }); Status = $status }
}
$plan = @($plan)

$planCsv = Join-Path $Root 'sort_plan.csv'
$plan | Export-Csv -LiteralPath $planCsv -NoTypeInformation -Encoding UTF8

$toMove = @($plan | Where-Object { $_.Status -eq 'move' })
Write-Host ''
Write-Host "Matched: $($toMove.Count)   Already in album: $(@($plan | Where-Object { $_.Status -like 'duplicate*' }).Count)   Not matched: $(@($plan | Where-Object { $_.Status -like 'unmatched*' }).Count)   Skipped: $(@($plan | Where-Object { $_.Status -like 'skipped*' }).Count)"
Write-Host ''
Write-Host 'Files per destination folder:'
$toMove | Group-Object Destination | Sort-Object Name | ForEach-Object {
    $new = if ($_.Group[0].NewFolder) { '  (new folder)' } else { '' }
    Write-Host ("  {0,4}  {1}{2}" -f $_.Count, $_.Name.Substring($Root.Length).TrimStart($Sep), $new)
}
$left = @($plan | Where-Object { $_.Status -ne 'move' })
if ($left) {
    Write-Host ''
    Write-Host 'Staying in Not Sorted:'
    $left | ForEach-Object { Write-Host "  $(Split-Path -Leaf $_.File)  --  $($_.Status)" }
}
Write-Host ''
Write-Host "Full plan saved to $planCsv"

if (-not $Apply) {
    Write-Host ''
    Write-Host 'Dry run only, nothing was moved. Check the plan, then run again with -Apply.' -ForegroundColor Yellow
    return
}

# ---------------------------------------------------------------------------
# Move
# ---------------------------------------------------------------------------
$logCsv = Join-Path $Root 'sort_log.csv'
$log = foreach ($p in $toMove) {
    if (-not (Test-Path -LiteralPath $p.Destination)) { [void](New-Item -ItemType Directory -Path $p.Destination) }
    $src = Get-Item -LiteralPath $p.File
    $target = Join-Path $p.Destination $src.Name
    if (Test-Path -LiteralPath $target) {
        if ((Get-Item -LiteralPath $target).Length -eq $src.Length) {
            [pscustomobject]@{ From = $src.FullName; To = $target; Result = 'skipped: same file already there' }
            continue
        }
        $n = 2
        do { $target = Join-Path $p.Destination ("{0} ({1}){2}" -f $src.BaseName, $n, $src.Extension); $n++ }
        while (Test-Path -LiteralPath $target)
    }
    Move-Item -LiteralPath $src.FullName -Destination $target
    [pscustomobject]@{ From = $src.FullName; To = $target; Result = 'moved' }
}
$log = @($log)
$log | Export-Csv -LiteralPath $logCsv -NoTypeInformation -Encoding UTF8
Write-Host ''
Write-Host "Moved $(@($log | Where-Object { $_.Result -eq 'moved' }).Count) files. Log: $logCsv" -ForegroundColor Green
